# Generated by Django 5.2.3 on 2025-06-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estates.estate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resident_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant'), ('landlord/landlady', 'Landlord/Landlady')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
