# Generated by Django 5.2.3 on 2025-06-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_user_estate_alter_user_home_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='estate_account_number',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='estate_bank_name',
        ),
        migrations.CreateModel(
            name='EstateBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='estates.estate')),
            ],
            options={
                'unique_together': {('estate', 'account_number')},
            },
        ),
    ]
