# Generated by Django 5.2.3 on 2025-06-25 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.estate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='resident_type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord/landlady', 'Landlord/Landlady', 'security', 'Security')], max_length=20, null=True, blank=True),
            preserve_default=False,
        ),

    ]
