# Generated by Django 5.2.3 on 2025-06-25 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_remove_estate_estate_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatebankaccount',
            name='account_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
