# Generated by Django 5.2.3 on 2025-06-25 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_estatebankaccount_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateleadership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to=settings.AUTH_USER_MODEL),
        ),
    ]
