# Generated by Django 5.2.3 on 2025-06-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_alter_estateleadership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateleadership',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to='estates.estate'),
        ),
        migrations.AlterField(
            model_name='estateleadership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
