# Generated by Django 5.2.3 on 2025-06-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_alter_estateleadership_estate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_dues', to='estates.estate'),
        ),
    ]
