# Generated by Django 5.2.3 on 2025-06-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_alter_due_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
