# Generated by Django 5.2.3 on 2025-07-01 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_resident', 'New Resident'), ('payment', 'Payment Evidence'), ('visitor_code', 'Visitor Code')], max_length=50)),
                ('description', models.TextField()),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='ID of related object (e.g., Resident, Payment, VisitorCode)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.estate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
