# Generated by Django 5.2.3 on 2025-07-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0009_activitylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duepayment',
            unique_together=set(),
        ),
    ]
