# Generated by Django 5.2.3 on 2025-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0010_alter_duepayment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resident_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant'), ('landlord/landlady', 'Landlord/Landlady'), ('security', 'Security')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Estate Admin'), ('resident', 'Resident'), ('security', 'Estate Security')], default='resident', max_length=20),
        ),
    ]
