# Generated by Django 5.2.3 on 2025-07-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0011_alter_user_resident_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_plan_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(help_text='Amount in kobo (e.g. ₦10,000 → 1000000)')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_customer_code', models.CharField(max_length=100)),
                ('paystack_subscription_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('next_billing_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='estates.estate')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estates.subscriptionplan')),
            ],
        ),
    ]
