# Generated by Django 5.2.3 on 2025-07-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0012_subscriptionplan_estatesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatesubscription',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
