# Generated by Django 5.2.3 on 2025-07-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0014_user_is_email_verified_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
