# Generated by Django 5.2.3 on 2025-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0015_user_password_reset_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='street_number',
        ),
        migrations.AddField(
            model_name='user',
            name='house_type',
            field=models.CharField(blank=True, choices=[('self_contained', 'Self Contained'), ('miniflat', 'Miniflat'), ('2bedroom', '2 Bedroom'), ('3bedroom', '3 Bedroom'), ('4bedroom', '4 Bedroom'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('townhouse', 'Townhouse'), ('other', 'Other')], max_length=20),
        ),
    ]
