# Generated by Django 5.2.3 on 2025-07-30 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0016_remove_user_street_number_user_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='estates.estate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
