# Generated by Django 5.2.3 on 2025-08-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0017_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatesubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='active', max_length=20),
        ),
    ]
