# Generated by Django 5.2.3 on 2025-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0018_alter_estatesubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatesubscription',
            name='email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
