# Generated by Django 5.2.3 on 2025-09-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0019_estatesubscription_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Generated receipt PDF for approved payments', null=True, upload_to='receipts/'),
        ),
    ]
