# Generated by Django 5.2.3 on 2025-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0020_duepayment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duepayment',
            name='payment_evidence',
            field=models.FileField(upload_to='payment_evidence/'),
        ),
    ]
