# Generated by Django 5.2.3 on 2025-09-25 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0022_usersubscription_delete_estatesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_subscription_code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estates.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
    ]
