# Generated by Django 5.2.3 on 2025-09-29 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0023_usersubscriptionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanOrDomesticStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(help_text='Artisan/Domestic staff role (e.g. Plumber, Cook, Cleaner)', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('unique_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=10)),
                ('removal_reason', models.TextField(blank=True, null=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisans_domestics', to='estates.estate')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisans_domestics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
