# Generated by Django 5.2.3 on 2025-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0024_artisanordomesticstaff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artisanordomesticstaff',
            constraint=models.UniqueConstraint(fields=('estate', 'phone_number'), name='unique_staff_in_estate'),
        ),
    ]
