# Generated by Django 5.2.3 on 2025-09-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0025_artisanordomesticstaff_unique_staff_in_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanordomesticstaff',
            name='unique_id',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
