# Generated by Django 5.2.3 on 2025-09-29 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0026_alter_artisanordomesticstaff_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('new_resident', 'New Resident'), ('payment', 'Payment Evidence'), ('visitor_code', 'Visitor Code'), ('Artisan/Domestic_Staff', 'New Artisan or Domestic Staff')], max_length=50),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fire', 'Fire'), ('intruder', 'Intruder'), ('medical', 'Medical Emergency'), ('electricity', 'Electricity Issue'), ('water', 'Water Leakage'), ('other', 'Other')], max_length=50)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='estates.estate')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
