# Generated by Django 5.2.3 on 2025-12-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_alter_user_estate_alter_user_home_address_and_more'),
        ('estates', '0027_alter_activitylog_type_alert'),
    ]

    operations = [
    ]
