# Generated by Django 5.2.3 on 2025-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0027_alter_activitylog_type_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('new_resident', 'New Resident'), ('payment', 'Payment Evidence'), ('visitor_code', 'Visitor Code'), ('Artisan/Domestic_Staff', 'New Artisan or Domestic Staff'), ('new_alert', 'New Alert')], max_length=50),
        ),
    ]
