# Generated by Django 5.2.3 on 2025-12-09 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0028_merge_20251203_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Emergency Alert'), ('payment', 'Payment'), ('due', 'Estate Due'), ('resident', 'New Resident'), ('artisan', 'Artisan/Staff'), ('announcement', 'Announcement'), ('approval', 'Approval Request'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('new_resident', 'New Resident'), ('payment', 'Payment Evidence'), ('visitor_code', 'Visitor Code'), ('Artisan/Domestic_Staff', 'New Artisan or Domestic Staff'), ('new_alert', 'New Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estates.estate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resident_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant'), ('landlord/landlady', 'Landlord/Landlady'), ('security', 'Security')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('auth', models.CharField(max_length=255)),
                ('p256dh', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
