# Generated by Django 5.2.3 on 2025-12-03 15:02

from django.db import migrations


def fill_null_estate_ids(apps, schema_editor):
    User = apps.get_model('estates', 'User')
    
    # Count how many users have null estate_id
    null_count = User.objects.filter(estate_id__isnull=True).count()
    
    if null_count > 0:
        # Option 1: Set a default estate for all null values
        # Replace 1 with your actual default estate ID
        default_estate_id = 1
        User.objects.filter(estate_id__isnull=True).update(estate_id=default_estate_id)
        
        # Option 2: Delete users without estates (uncomment if preferred)
        # User.objects.filter(estate_id__isnull=True).delete()


def reverse_fill(apps, schema_editor):
    # Reverse operation (optional)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0028_merge_20251203_1452'),
    ]

    operations = [
        migrations.RunPython(fill_null_estate_ids, reverse_fill),
    ]