# Generated by Django 5.2.3 on 2025-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0029_notification_action_url_notification_is_push_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Emergency Alert'), ('payment', 'Payment'), ('due', 'Estate Due'), ('resident', 'New Resident'), ('artisan', 'Artisan/Staff'), ('announcement', 'Announcement'), ('approval', 'Approval Request'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
