// src/sw.ts
// Custom Service Worker for Vite PWA with Push Notifications
/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';


// Extend NotificationOptions to include sound property
interface ExtendedNotificationOptions extends NotificationOptions {
  sound?: string;
}

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Take control of all pages as soon as the service worker is activated
self.skipWaiting();
clientsClaim();

// ============= PUSH NOTIFICATION HANDLERS =============

// Handle incoming push notifications
self.addEventListener('push', (event: PushEvent) => {
  console.log('[Service Worker] Push notification received', event);
  
  let data = {
    title: 'EstatePadi',
    body: 'You have a new notification',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    url: '/',
    notification_id: null,
    notification_type: 'general',
    requireInteraction: false,
  };
  
  if (event.data) {
    try {
      const pushData = event.data.json();
      data = { ...data, ...pushData };
    } catch (e) {
      console.error('[Service Worker] Error parsing push data:', e);
      data.body = event.data.text();
    }
  }
  
  const options: ExtendedNotificationOptions & { vibrate?: number[] } = {
    body: data.body,
    icon: data.icon || '/icons/icon-192x192.png',
    badge: data.badge || '/icons/icon-192x192.png',
    vibrate: [200, 100, 200],
    tag: `estatepadi-${data.notification_id || Date.now()}`,
    requireInteraction: data.requireInteraction,
    sound: 'default', 
    data: {
      url: data.url || '/',
      notificationId: data.notification_id,
      notificationType: data.notification_type,
      dateOfArrival: Date.now(),
    },
  };
  
  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[Service Worker] Notification clicked:', event);
  
  event.notification.close();
  
  const urlToOpen = event.notification.data?.url || '/';
  
  event.waitUntil(
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true
    }).then((windowClients) => {
      // Check if there's already a window open with this URL
      for (const client of windowClients) {
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Handle notification close events (optional - for analytics)
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('[Service Worker] Notification closed:', event);
  // You can track notification close events here if needed
});

// Handle service worker messages
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});